version: '3'

vars:
  MVN: "mvn"
  DC_DIR: "deployment/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"
  APPS_DC_FILE: "{{.DC_DIR}}/apps.yml"

tasks:
  default:
    cmds:
      - task: test

  test:
    deps: [ format ]
    cmds:
      - "{{.MVN}} clean verify"

  format:
    cmds:
      - "{{.MVN}} spotless:apply"

  build:
    cmds:
      #      as log, as we don't have the catalog service as Dockerize, we used below command.
      #      - "{{.MVN}} verify"
      - "{{.MVN}}  -pl catalog-service spring-boot:build-image -DskipTests"
  start_infra:
    cmds:
      - docker compose -f "{{.INFRA_DC_FILE}}" up -d

  stop_infra:
    cmds:
      - docker compose -f "{{.INFRA_DC_FILE}}" stop
      - docker compose -f "{{.INFRA_DC_FILE}}" rm -f

  restart_infra:
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  start:
    deps: [ build ]
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} up -d"

  stop:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} rm -f"

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start


#  sleep:
#    vars:
#      DURATION: '{{default 5 .DURATION}}'
#    cmds:
#      - sleep {{.DURATION}}
