version: '3'

vars:
  MVN: "mvn"
  DC_DIR: "deployment/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"
  APPS_DC_FILE: "{{.DC_DIR}}/apps.yml"

tasks:
  default:
    cmds:
      - task: test

  test:
    deps: [ format ]
    cmds:
      - "{{.MVN}} clean verify"

  format:
    cmds:
      - "{{.MVN}} spotless:apply"

  build:

    cmds:
      #      as log, as we don't have the catalog service as Dockerize, we used below command.
      #      - "{{.MVN}} verify"
      #      after below command Image is written into the local Docker daemon
      - "{{.MVN}} -pl catalog-service spring-boot:build-image -DskipTests"
      - "{{.MVN}} -pl order-service spring-boot:build-image -DskipTests"
      - "{{.MVN}} -pl notification-service spring-boot:build-image -DskipTests"
      - "{{.MVN}} -pl api-gateway spring-boot:build-image -DskipTests"
      - "{{.MVN}} -pl bookstore-webapp spring-boot:build-image -DskipTests"

# TODO: Explore parallel builds to speed up image creation
#To fully maximize performance, you can use both:
#  Maven Build in Parallel: mvn -pl catalog-service,order-service -T 4 -parallel spring-boot:build-image -DskipTests
#  Docker Compose Start in Parallel: docker compose --parallel up -d

  start_infra:
    cmds:
      - docker compose -f "{{.INFRA_DC_FILE}}" up -d

  stop_infra:
    cmds:
      - docker compose -f "{{.INFRA_DC_FILE}}" stop
      - docker compose -f "{{.INFRA_DC_FILE}}" rm -f

  restart_infra:
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  start:
    deps: [ build ]
    cmds:
  # docker compose reads infra.yml and apps.yml, merges them into one composed
  #  model (services, networks, volumes, depends_on, envs, ports).
  #  Docker Engine (inside Docker Desktop VM) creates a project network
  #  Docker Engine creates and starts infra containers (first)
  #  After infra is healthy, Docker Engine starts **app containers** (second)
  #   -catalog-service container is created from the local image produced earlier. Docker attaches it with same project
  #   network, mounts volumes (if any), injects environment variables defined in apps.yml,and maps ports (8082:8082).
  # Inside the running catalog-service process, Spring Boot starts
  #   -Spring Boot reads configuration in its precedence order (see later). It receives DB connection details via
  #  environment variables (injected by Compose). Those values override defaults in application.properties where
  #  placeholders are used (e.g. ${DB_URL:...}).
  #  Runtime connectivity
  #   - catalog-service resolves catalog-db via Docker network DNS, opens a JDBC connection to Postgres, registers
  #     health checks, exposes REST endpoints on port 8082.
  # Result: both containers run inside Docker Desktop’s Linux VM. The local Docker daemon manages their lifecycle,
  #  resource usage, logs, volumes, and network routing to your host.
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} up -d"

  stop:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} rm -f"

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start

  sleep:
    vars:
      DURATION: '{{default 5 .DURATION}}'
    cmds:
      - powershell -Command "Start-Sleep -Seconds {{.DURATION}}"
#  sleep:
#    vars:
#      DURATION: '{{default 5 .DURATION}}'
#    cmds:
#      - sleep {{.DURATION}}
