name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'
      #      - 'main' we can change name whatever we want

  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Check Maven version and print into logs
        run: mvn -v

      #      Do not let CI auto-fix code (i.e., avoid running spotless:apply in CI and auto-commit).
      #      CI should fail and ask developer to fix locally. Use pre-commit hooks / IDE formatting to avoid CI failures.
      #      - name: Fix formatting
      #        run: ./mvnw spotless:apply

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catalog-service

      - if: ${{ github.ref != 'refs/heads/main' }}
        name: Skip Message
        run: |
          echo "Skipped Docker build: Not on main branch (current: ${{ github.ref }})"